title: Titles tesss
url: ''
favicon: /images/favicon-isomer.ico
colors:
  primary-color: '#ff0000'
  secondary-color: '#43d65b'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'
collections:
  super duper extra hyper ultra double triple quadruple long folder name:
    permalink: '/:collection/:path/:title'
    output: true
  hello-new-test-folder:
    output: true
  new-collection-test:
    output: true
  going-to-delete:
    output: true
  test-555:
    output: true
  POP lohz:
    output: true
permalink: none
baseurl: ''
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ''
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test
resources_name: resource-room-create-test
shareicon: /images/Thinking-of-getting-a-cat.png
facebook-pixel: ''
google_analytics: ''
is_government: 'true'
